language: java
services:
  - mysql

test:
  adapter: mysql2
  database: alderalifetest
  username: springuser
  encoding: utf8

before_install:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS alderalifetest;'
  - mysql -e 'CREATE USER 'springuser'@'localhost' IDENTIFIED BY 'ThePassword'';
  - mysql -e 'GRANT ALL PRIVILEGES ON alderalifetest.* TO 'springuser'@'localhost'';