language: java
services:
  - mysql

test:
  adapter: mysql2
  database: alderalifetest
  username: travis
  encoding: utf8

before_install:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS alderalifetest;'

script: ./mvnw clean install -DskipTests=true