language: java
services:
  - mysql

test:
  adapter: mysql2
  database: alderalifetest
  username: springuser
  encoding: utf8

before_install:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS alderalifetest;'
  - sudo mysql -e "use mysql; update user set authentication_string=PASSWORD('ThePassword') where User='root'; update user set plugin='mysql_native_password';FLUSH PRIVILEGES;"
  - sudo service mysql restart